version: '3'

services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  db:
    container_name: db
    restart: always
    image: postgres:13.4-alpine
    environment:
      # POSTGRES_DB: postgres
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "5435:5432"

volumes:
  data:
  node_modules:
